[package]
name = "ftcwa-live"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda-web = { version = "0.2.0", features=["rocket05"] }
rocket = "0.5.0-rc.2"
strum = "0.24"
strum_macros = "0.24"

[features]
lambda = []
