[package]
name = "ftcwa-live"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda-web = { version = "0.2.0", features=["rocket05"] }
once_cell = "1.20.2"
phf = { version = "0.11.2", features=["macros"] }
rocket = "0.5.0"

[features]
lambda = []
