name: Build & Deploy

on:
  push:
    branches: [ "main" ]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    env:
      FORCE_COLOR: 1
    steps:
    - uses: actions/checkout@v4
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run tests
      run: cargo test
      working-directory: ./lambda
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.0
      with:
        node-version: lts/*
        cache: "npm"
    - name: Install dependencies
      run: npm ci
    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4.0.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-west-2'
    - name: Deploy cdk
      run: npm run cdk deploy -- --require-approval never
