name: Dry Run Build

on:
  pull_request:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
        - uses: actions/checkout@v4
        - name: Cache dependencies
          uses: actions/cache@v4
          with:
            path: |
              ~/.cargo/bin/
              ~/.cargo/registry/index/
              ~/.cargo/registry/cache/
              ~/.cargo/git/db/
              target/
            key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        - name: Run tests
          run: cargo test
          working-directory: ./lambda
        - name: Setup Node.js environment
          uses: actions/setup-node@v4.0.0
          with:
            node-version: lts/*
            cache: "npm"
        - name: Install dependencies
          run: npm ci
        - name: Configure aws credentials
          uses: aws-actions/configure-aws-credentials@v4.0.1
          with:
            aws-access-key-id: ${{ secrets.AWS_READ_ONLY_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_READ_ONLY_ACCESS_KEY_SECRET }}
            aws-region: 'us-west-2'
        - name: Build
          run: npm run cdk diff
          working-directory: ./lambda
